fix(be):   ADP-2285 update CI workflow, dependencies, and config for Node.js 20 support
blindspot-security/myrror-cli pull request #5
Opened 2024-05-29 11:10 UTC by leovvay

- Add GitHub Actions workflow to run tests on PRs targeting main branch
- Upgrade dependencies and devDependencies to latest versions
- Update Dockerfile to use Node.js 20
- Adjust config and test files to reflect new API URL and dependency changes

2024-05-29 11:12 UTC, leovvay commented
ADP-2285

2024-06-02 08:06 UTC, icedrone requested changes

2024-06-02 08:06 UTC, icedrone commented on .github/workflows/tests.yaml
> +        uses: actions/checkout@v2
```suggestion
        uses: actions/checkout@v4
```

2024-06-02 08:06 UTC, icedrone commented on .github/workflows/tests.yaml
> +        uses: actions/setup-node@v2
```suggestion
        uses: actions/setup-node@v4
```

2024-06-04 15:53 UTC, icedrone approved these changes

2024-06-04 15:56 UTC, merged